### ISSUE TITLE
可否展示所属项目

### ISSUE THREAD

**Issue by EggsBlue** [threefish/NutzCodeInsight#12]
两个模块有相同的路由路径,会查找出两个一模一样的但是区分不出项目,只有点进去了才能看到,可否在后面展示出所属模块?

**Comment by threefish** [comment]
下个版本加上

**Comment by Leewell1989** [comment]
安装好以后报错，java.lang.NoSuchMethodError
![Snipaste_2019-08-08_09-49-21](https://user-images.githubusercontent.com/6307803/62669352-d7b06880-b9c1-11e9-95ab-62bd29e812d6.png)

**Comment by threefish** [comment]
@Leewell1989 如果不影响使用，可以不用管，如影响使用，建议idea升级至2019.1.1及以上.

**Comment by threefish** [comment]
[it's fixed](https://github.com/threefish/NutzCodeInsight/pull/13 ) @EggsBlue
