### ISSUE TITLE
希望支持freemarker

### ISSUE THREAD

**Issue by EggsBlue** [threefish/NutzCodeInsight#2]
希望有时间支持一下freeemarker,赞一个!

**Comment by threefish** [comment]
@TopCoderMyDream 这个我要先看看freemarker的idea插件能不能做再决定

**Comment by threefish** [comment]
@TopCoderMyDream idea中freemaker默认是支持的，并且本插件也支持资源文件的快速跳转


![freemarker](https://user-images.githubusercontent.com/6268640/34703969-e57dd81e-f530-11e7-95ce-2c4eef9eecef.png)

**Comment by EggsBlue** [comment]
好的我试试
