### ISSUE TITLE
无法设置模板

### ISSUE THREAD

**Issue by howe** [threefish/NutzCodeInsight#3]
@Ok("beetl:/order/hallList.btl")
如上 提示 beetl 重复 哈哈

**Comment by threefish** [comment]
@howe 我没看明白你说的是什么意思，出了什么问题吗？

**Comment by howe** [comment]
![TIM截图20180209163704.jpg](https://i.loli.net/2018/02/09/5a7d5e2e19c7f.jpg)
![TIM截图20180209163744.jpg](https://i.loli.net/2018/02/09/5a7d5e2e1a17d.jpg)

我直接截图吧

**Comment by threefish** [comment]
@howe 明白了，我抽空解决下

**Comment by threefish** [comment]
@howe 试试[1.8.2的包](https://github.com/threefish/NutzCodeInsight/blob/master/release/NutzCodeInsight1.8.2.jar)

**Comment by howe** [comment]
可以了
